# docker networks
networks:
  splunk_net: # network for central gateway node, redis distributed lock, and worker nodes
    driver: bridge
  elastic_net: # network for elastic search cluster
    driver: bridge

# volumes (storage files) for elastic cluster nodes
volumes:
  elastic_node_0_data:
    driver: local
  elastic_node_1_data:
    driver: local
  elastic_node_2_data:
    driver: local

# docker service containers
services:
  # container for redis distributed lock
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - splunk_net

  # elasticsearch multi-node cluster from https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docker.html 
  # container for elastic search cluster node 0 
  elastic_node_0:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elastic_node_0
    environment:
      - node.name=elastic_node_0
      - cluster.name=elastic_search_cluster
      - discovery.seed_hosts=elastic_node_1,elastic_node_2
      - cluster.initial_master_nodes=elastic_node_0,elastic_node_1,elastic_node_2
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_node_0_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic_net

  # container for elastic search cluster node 1 
  elastic_node_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elastic_node_1
    environment:
      - node.name=elastic_node_1
      - cluster.name=elastic_search_cluster
      - discovery.seed_hosts=elastic_node_0,elastic_node_2
      - cluster.initial_master_nodes=elastic_node_0,elastic_node_1,elastic_node_2
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_node_1_data:/usr/share/elasticsearch/data
    networks:
      - elastic_net

  # container for elastic search cluster node 2
  elastic_node_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elastic_node_2
    environment:
      - node.name=elastic_node_2
      - cluster.name=elastic_search_cluster
      - discovery.seed_hosts=elastic_node_0,elastic_node_1
      - cluster.initial_master_nodes=elastic_node_0,elastic_node_1,elastic_node_2
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_node_2_data:/usr/share/elasticsearch/data
    networks:
      - elastic_net
  
  # central gateway server (client contact point, and worker node coordinator)
  central_gateway:
    # build for python script
    build: .
    container_name: central_gateway
    command: python3 CentralNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
    depends_on:
      - redis
      - elastic_node_0
      - elastic_node_1
      - elastic_node_2

  # worker node containers (total of 5, starting from 0-4)
  worker_node_0:
    build: .
    container_name: worker_node_0
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - elastic_net
    depends_on:
      - redis
      - central_gateway
      - elastic_node_0
      - elastic_node_1
      - elastic_node_2

  worker_node_1:
    build: .
    container_name: worker_node_1
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - elastic_net
    depends_on:
      - redis
      - central_gateway
      - elastic_node_0
      - elastic_node_1
      - elastic_node_2

  worker_node_2:
    build: .
    container_name: worker_node_2
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - elastic_net
    depends_on:
      - redis
      - central_gateway
      - elastic_node_0
      - elastic_node_1
      - elastic_node_2

  worker_node_3:
    build: .
    container_name: worker_node_3
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - elastic_net
    depends_on:
      - redis
      - central_gateway
      - elastic_node_0
      - elastic_node_1
      - elastic_node_2

  worker_node_4:
    build: .
    container_name: worker_node_4
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - elastic_net
    depends_on:
      - redis
      - central_gateway
      - elastic_node_0
      - elastic_node_1
      - elastic_node_2