networks:
  splunk_net:
    driver: bridge
  cassandra_net:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - splunk_net

  cassandra_seed:
    image: cassandra:latest
    container_name: cassandra_seed
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=CASSANDRA-CLUSTER
      - CASSANDRA_RACK=CASSANDRA-RACK
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=CASSANDRA-DATACENTER
    networks:
      - cassandra_net

  cassandra_node_0:
    image: cassandra:latest
    container_name: cassandra_node_0
    environment:
      - CASSANDRA_CLUSTER_NAME=CASSANDRA-CLUSTER
      - CASSANDRA_SEEDS=cassandra_seed
      - CASSANDRA_RACK=CASSANDRA-RACK
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=CASSANDRA-DATACENTER
    networks:
      - cassandra_net
    depends_on:
      - cassandra_seed

  cassandra_node_1:
    image: cassandra:latest
    container_name: cassandra_node_1
    environment:
      - CASSANDRA_CLUSTER_NAME=CASSANDRA-CLUSTER
      - CASSANDRA_SEEDS=cassandra_seed
      - CASSANDRA_RACK=CASSANDRA-RACK
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=CASSANDRA-DATACENTER
    networks:
      - cassandra_net
    depends_on:
      - cassandra_seed

  cassandra_node_2:
    image: cassandra:latest
    container_name: cassandra_node_2
    environment:
      - CASSANDRA_CLUSTER_NAME=CASSANDRA-CLUSTER
      - CASSANDRA_SEEDS=cassandra_seed
      - CASSANDRA_RACK=CASSANDRA-RACK
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=CASSANDRA-DATACENTER
    networks:
      - cassandra_net
    depends_on:
      - cassandra_seed
  
  central_gateway:
    build: .
    container_name: central_gateway
    command: python3 CentralNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
    depends_on:
      - redis
      - cassandra_seed
      - cassandra_node_0
      - cassandra_node_1
      - cassandra_node_2

  worker_node_0:
    build: .
    container_name: worker_node_0
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - cassandra_net
    depends_on:
      - redis
      - central_gateway
      - cassandra_seed
      - cassandra_node_0
      - cassandra_node_1
      - cassandra_node_2

  worker_node_1:
    build: .
    container_name: worker_node_1
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - cassandra_net
    depends_on:
      - redis
      - central_gateway
      - cassandra_seed
      - cassandra_node_0
      - cassandra_node_1
      - cassandra_node_2

  worker_node_2:
    build: .
    container_name: worker_node_2
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - cassandra_net
    depends_on:
      - redis
      - central_gateway
      - cassandra_seed
      - cassandra_node_0
      - cassandra_node_1
      - cassandra_node_2

  worker_node_3:
    build: .
    container_name: worker_node_3
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - cassandra_net
    depends_on:
      - redis
      - central_gateway
      - cassandra_seed
      - cassandra_node_0
      - cassandra_node_1
      - cassandra_node_2

  worker_node_4:
    build: .
    container_name: worker_node_4
    command: python3 WorkerNode.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - splunk_net
      - cassandra_net
    depends_on:
      - redis
      - central_gateway
      - cassandra_seed
      - cassandra_node_0
      - cassandra_node_1
      - cassandra_node_2