# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mini_splunk_protobuf_pb2 as mini__splunk__protobuf__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mini_splunk_protobuf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MiniSplunkStub:
    """Service Interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
                '/MiniSplunk/Ingest',
                request_serializer=mini__splunk__protobuf__pb2.LogBatch.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.IngestStatus.FromString,
                _registered_method=True)
        self.Purge = channel.unary_unary(
                '/MiniSplunk/Purge',
                request_serializer=mini__splunk__protobuf__pb2.PurgeRequest.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.RequestStatus.FromString,
                _registered_method=True)
        self.SearchDate = channel.unary_stream(
                '/MiniSplunk/SearchDate',
                request_serializer=mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.LogBatch.FromString,
                _registered_method=True)
        self.SearchHost = channel.unary_stream(
                '/MiniSplunk/SearchHost',
                request_serializer=mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.LogBatch.FromString,
                _registered_method=True)
        self.SearchDaemon = channel.unary_stream(
                '/MiniSplunk/SearchDaemon',
                request_serializer=mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.LogBatch.FromString,
                _registered_method=True)
        self.SearchSeverity = channel.unary_stream(
                '/MiniSplunk/SearchSeverity',
                request_serializer=mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.LogBatch.FromString,
                _registered_method=True)
        self.SearchKeyword = channel.unary_stream(
                '/MiniSplunk/SearchKeyword',
                request_serializer=mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.LogBatch.FromString,
                _registered_method=True)
        self.CountKeyword = channel.unary_unary(
                '/MiniSplunk/CountKeyword',
                request_serializer=mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
                response_deserializer=mini__splunk__protobuf__pb2.LogCount.FromString,
                _registered_method=True)


class MiniSplunkServicer:
    """Service Interface
    """

    def Ingest(self, request, context):
        """Service for File Ingests. Accepts a stream (flow) of `LogString` messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Purge(self, request, context):
        """Service for Purging Logs. Accepts a `PurgeRequest` message to signal Server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDate(self, request, context):
        """Service for filtering logs based on Date criterion. Returns a stream of 0-n `LogString` messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchHost(self, request, context):
        """Service for filtering logs based on Hostname criterion. Returns a stream of 0-n `LogString` messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDaemon(self, request, context):
        """Service for filtering logs based on Process criterion. Returns a stream of 0-n `LogString` messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSeverity(self, request, context):
        """Service for filtering logs based on Severity criterion. Returns a stream of 0-n `LogString` messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKeyword(self, request, context):
        """Service for filtering logs based on Keyword/s criterion. Returns a stream of 0-n `LogString` messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountKeyword(self, request, context):
        """Service for filtering logs based on Keyword/s criterion and accumulating matches. Returns `LogCount` match amount message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MiniSplunkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=mini__splunk__protobuf__pb2.LogBatch.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.IngestStatus.SerializeToString,
            ),
            'Purge': grpc.unary_unary_rpc_method_handler(
                    servicer.Purge,
                    request_deserializer=mini__splunk__protobuf__pb2.PurgeRequest.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.RequestStatus.SerializeToString,
            ),
            'SearchDate': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchDate,
                    request_deserializer=mini__splunk__protobuf__pb2.QueryRequest.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.LogBatch.SerializeToString,
            ),
            'SearchHost': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchHost,
                    request_deserializer=mini__splunk__protobuf__pb2.QueryRequest.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.LogBatch.SerializeToString,
            ),
            'SearchDaemon': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchDaemon,
                    request_deserializer=mini__splunk__protobuf__pb2.QueryRequest.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.LogBatch.SerializeToString,
            ),
            'SearchSeverity': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchSeverity,
                    request_deserializer=mini__splunk__protobuf__pb2.QueryRequest.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.LogBatch.SerializeToString,
            ),
            'SearchKeyword': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchKeyword,
                    request_deserializer=mini__splunk__protobuf__pb2.QueryRequest.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.LogBatch.SerializeToString,
            ),
            'CountKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.CountKeyword,
                    request_deserializer=mini__splunk__protobuf__pb2.QueryRequest.FromString,
                    response_serializer=mini__splunk__protobuf__pb2.LogCount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MiniSplunk', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MiniSplunk', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MiniSplunk:
    """Service Interface
    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiniSplunk/Ingest',
            mini__splunk__protobuf__pb2.LogBatch.SerializeToString,
            mini__splunk__protobuf__pb2.IngestStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Purge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiniSplunk/Purge',
            mini__splunk__protobuf__pb2.PurgeRequest.SerializeToString,
            mini__splunk__protobuf__pb2.RequestStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MiniSplunk/SearchDate',
            mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
            mini__splunk__protobuf__pb2.LogBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MiniSplunk/SearchHost',
            mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
            mini__splunk__protobuf__pb2.LogBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDaemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MiniSplunk/SearchDaemon',
            mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
            mini__splunk__protobuf__pb2.LogBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSeverity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MiniSplunk/SearchSeverity',
            mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
            mini__splunk__protobuf__pb2.LogBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MiniSplunk/SearchKeyword',
            mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
            mini__splunk__protobuf__pb2.LogBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MiniSplunk/CountKeyword',
            mini__splunk__protobuf__pb2.QueryRequest.SerializeToString,
            mini__splunk__protobuf__pb2.LogCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
