# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mini_splunk_protobuf.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mini_splunk_protobuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amini_splunk_protobuf.proto\" \n\x0cIngestStatus\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\">\n\x08LogBatch\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\x03\x12\x10\n\x08messages\x18\x03 \x03(\t\"0\n\x0cQueryRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x10\n\x08\x61rgument\x18\x02 \x01(\t\"\x0e\n\x0cPurgeRequest\"\x19\n\x08LogCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"\x1f\n\rRequestStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xdd\x02\n\nMiniSplunk\x12\"\n\x06Ingest\x12\t.LogBatch\x1a\r.IngestStatus\x12&\n\x05Purge\x12\r.PurgeRequest\x1a\x0e.RequestStatus\x12(\n\nSearchDate\x12\r.QueryRequest\x1a\t.LogBatch0\x01\x12(\n\nSearchHost\x12\r.QueryRequest\x1a\t.LogBatch0\x01\x12*\n\x0cSearchDaemon\x12\r.QueryRequest\x1a\t.LogBatch0\x01\x12,\n\x0eSearchSeverity\x12\r.QueryRequest\x1a\t.LogBatch0\x01\x12+\n\rSearchKeyword\x12\r.QueryRequest\x1a\t.LogBatch0\x01\x12(\n\x0c\x43ountKeyword\x12\r.QueryRequest\x1a\t.LogCountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mini_splunk_protobuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTSTATUS']._serialized_start=30
  _globals['_INGESTSTATUS']._serialized_end=62
  _globals['_LOGBATCH']._serialized_start=64
  _globals['_LOGBATCH']._serialized_end=126
  _globals['_QUERYREQUEST']._serialized_start=128
  _globals['_QUERYREQUEST']._serialized_end=176
  _globals['_PURGEREQUEST']._serialized_start=178
  _globals['_PURGEREQUEST']._serialized_end=192
  _globals['_LOGCOUNT']._serialized_start=194
  _globals['_LOGCOUNT']._serialized_end=219
  _globals['_REQUESTSTATUS']._serialized_start=221
  _globals['_REQUESTSTATUS']._serialized_end=252
  _globals['_MINISPLUNK']._serialized_start=255
  _globals['_MINISPLUNK']._serialized_end=604
# @@protoc_insertion_point(module_scope)
