// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mini_splunk_protobuf.proto

#include "mini_splunk_protobuf.pb.h"
#include "mini_splunk_protobuf.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* MiniSplunk_method_names[] = {
  "/MiniSplunk/Ingest",
  "/MiniSplunk/Purge",
  "/MiniSplunk/SearchDate",
  "/MiniSplunk/SearchHost",
  "/MiniSplunk/SearchDaemon",
  "/MiniSplunk/SearchSeverity",
  "/MiniSplunk/SearchKeyword",
  "/MiniSplunk/CountKeyword",
};

std::unique_ptr< MiniSplunk::Stub> MiniSplunk::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MiniSplunk::Stub> stub(new MiniSplunk::Stub(channel));
  return stub;
}

MiniSplunk::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Ingest_(MiniSplunk_method_names[0], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_Purge_(MiniSplunk_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchDate_(MiniSplunk_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchHost_(MiniSplunk_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchDaemon_(MiniSplunk_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchSeverity_(MiniSplunk_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchKeyword_(MiniSplunk_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CountKeyword_(MiniSplunk_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientWriter< ::LogString>* MiniSplunk::Stub::IngestRaw(::grpc::ClientContext* context, ::RequestStatus* response) {
  return ::grpc_impl::internal::ClientWriterFactory< ::LogString>::Create(channel_.get(), rpcmethod_Ingest_, context, response);
}

void MiniSplunk::Stub::experimental_async::Ingest(::grpc::ClientContext* context, ::RequestStatus* response, ::grpc::experimental::ClientWriteReactor< ::LogString>* reactor) {
  ::grpc_impl::internal::ClientCallbackWriterFactory< ::LogString>::Create(stub_->channel_.get(), stub_->rpcmethod_Ingest_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::LogString>* MiniSplunk::Stub::AsyncIngestRaw(::grpc::ClientContext* context, ::RequestStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::LogString>::Create(channel_.get(), cq, rpcmethod_Ingest_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::LogString>* MiniSplunk::Stub::PrepareAsyncIngestRaw(::grpc::ClientContext* context, ::RequestStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::LogString>::Create(channel_.get(), cq, rpcmethod_Ingest_, context, response, false, nullptr);
}

::grpc::Status MiniSplunk::Stub::Purge(::grpc::ClientContext* context, const ::PurgeRequest& request, ::RequestStatus* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Purge_, context, request, response);
}

void MiniSplunk::Stub::experimental_async::Purge(::grpc::ClientContext* context, const ::PurgeRequest* request, ::RequestStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Purge_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::Purge(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::RequestStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Purge_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::Purge(::grpc::ClientContext* context, const ::PurgeRequest* request, ::RequestStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Purge_, context, request, response, reactor);
}

void MiniSplunk::Stub::experimental_async::Purge(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::RequestStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Purge_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RequestStatus>* MiniSplunk::Stub::AsyncPurgeRaw(::grpc::ClientContext* context, const ::PurgeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::RequestStatus>::Create(channel_.get(), cq, rpcmethod_Purge_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::RequestStatus>* MiniSplunk::Stub::PrepareAsyncPurgeRaw(::grpc::ClientContext* context, const ::PurgeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::RequestStatus>::Create(channel_.get(), cq, rpcmethod_Purge_, context, request, false);
}

::grpc::Status MiniSplunk::Stub::SearchDate(::grpc::ClientContext* context, const ::QueryRequest& request, ::LogResults* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SearchDate_, context, request, response);
}

void MiniSplunk::Stub::experimental_async::SearchDate(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchDate_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchDate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchDate_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchDate(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchDate_, context, request, response, reactor);
}

void MiniSplunk::Stub::experimental_async::SearchDate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchDate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::AsyncSearchDateRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchDate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::PrepareAsyncSearchDateRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchDate_, context, request, false);
}

::grpc::Status MiniSplunk::Stub::SearchHost(::grpc::ClientContext* context, const ::QueryRequest& request, ::LogResults* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SearchHost_, context, request, response);
}

void MiniSplunk::Stub::experimental_async::SearchHost(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchHost_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchHost(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchHost_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchHost(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchHost_, context, request, response, reactor);
}

void MiniSplunk::Stub::experimental_async::SearchHost(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchHost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::AsyncSearchHostRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchHost_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::PrepareAsyncSearchHostRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchHost_, context, request, false);
}

::grpc::Status MiniSplunk::Stub::SearchDaemon(::grpc::ClientContext* context, const ::QueryRequest& request, ::LogResults* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SearchDaemon_, context, request, response);
}

void MiniSplunk::Stub::experimental_async::SearchDaemon(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchDaemon_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchDaemon(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchDaemon_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchDaemon(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchDaemon_, context, request, response, reactor);
}

void MiniSplunk::Stub::experimental_async::SearchDaemon(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchDaemon_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::AsyncSearchDaemonRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchDaemon_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::PrepareAsyncSearchDaemonRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchDaemon_, context, request, false);
}

::grpc::Status MiniSplunk::Stub::SearchSeverity(::grpc::ClientContext* context, const ::QueryRequest& request, ::LogResults* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SearchSeverity_, context, request, response);
}

void MiniSplunk::Stub::experimental_async::SearchSeverity(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchSeverity_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchSeverity(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchSeverity_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchSeverity(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchSeverity_, context, request, response, reactor);
}

void MiniSplunk::Stub::experimental_async::SearchSeverity(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchSeverity_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::AsyncSearchSeverityRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchSeverity_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::PrepareAsyncSearchSeverityRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchSeverity_, context, request, false);
}

::grpc::Status MiniSplunk::Stub::SearchKeyword(::grpc::ClientContext* context, const ::QueryRequest& request, ::LogResults* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SearchKeyword_, context, request, response);
}

void MiniSplunk::Stub::experimental_async::SearchKeyword(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchKeyword_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchKeyword(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SearchKeyword_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::SearchKeyword(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchKeyword_, context, request, response, reactor);
}

void MiniSplunk::Stub::experimental_async::SearchKeyword(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogResults* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SearchKeyword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::AsyncSearchKeywordRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchKeyword_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::LogResults>* MiniSplunk::Stub::PrepareAsyncSearchKeywordRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogResults>::Create(channel_.get(), cq, rpcmethod_SearchKeyword_, context, request, false);
}

::grpc::Status MiniSplunk::Stub::CountKeyword(::grpc::ClientContext* context, const ::QueryRequest& request, ::LogCount* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CountKeyword_, context, request, response);
}

void MiniSplunk::Stub::experimental_async::CountKeyword(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogCount* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CountKeyword_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::CountKeyword(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogCount* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CountKeyword_, context, request, response, std::move(f));
}

void MiniSplunk::Stub::experimental_async::CountKeyword(::grpc::ClientContext* context, const ::QueryRequest* request, ::LogCount* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CountKeyword_, context, request, response, reactor);
}

void MiniSplunk::Stub::experimental_async::CountKeyword(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::LogCount* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CountKeyword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::LogCount>* MiniSplunk::Stub::AsyncCountKeywordRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogCount>::Create(channel_.get(), cq, rpcmethod_CountKeyword_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::LogCount>* MiniSplunk::Stub::PrepareAsyncCountKeywordRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::LogCount>::Create(channel_.get(), cq, rpcmethod_CountKeyword_, context, request, false);
}

MiniSplunk::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< MiniSplunk::Service, ::LogString, ::RequestStatus>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReader<::LogString>* reader,
             ::RequestStatus* resp) {
               return service->Ingest(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniSplunk::Service, ::PurgeRequest, ::RequestStatus>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::PurgeRequest* req,
             ::RequestStatus* resp) {
               return service->Purge(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniSplunk::Service, ::QueryRequest, ::LogResults>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::QueryRequest* req,
             ::LogResults* resp) {
               return service->SearchDate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniSplunk::Service, ::QueryRequest, ::LogResults>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::QueryRequest* req,
             ::LogResults* resp) {
               return service->SearchHost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniSplunk::Service, ::QueryRequest, ::LogResults>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::QueryRequest* req,
             ::LogResults* resp) {
               return service->SearchDaemon(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniSplunk::Service, ::QueryRequest, ::LogResults>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::QueryRequest* req,
             ::LogResults* resp) {
               return service->SearchSeverity(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniSplunk::Service, ::QueryRequest, ::LogResults>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::QueryRequest* req,
             ::LogResults* resp) {
               return service->SearchKeyword(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniSplunk_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniSplunk::Service, ::QueryRequest, ::LogCount>(
          [](MiniSplunk::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::QueryRequest* req,
             ::LogCount* resp) {
               return service->CountKeyword(ctx, req, resp);
             }, this)));
}

MiniSplunk::Service::~Service() {
}

::grpc::Status MiniSplunk::Service::Ingest(::grpc::ServerContext* context, ::grpc::ServerReader< ::LogString>* reader, ::RequestStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniSplunk::Service::Purge(::grpc::ServerContext* context, const ::PurgeRequest* request, ::RequestStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniSplunk::Service::SearchDate(::grpc::ServerContext* context, const ::QueryRequest* request, ::LogResults* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniSplunk::Service::SearchHost(::grpc::ServerContext* context, const ::QueryRequest* request, ::LogResults* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniSplunk::Service::SearchDaemon(::grpc::ServerContext* context, const ::QueryRequest* request, ::LogResults* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniSplunk::Service::SearchSeverity(::grpc::ServerContext* context, const ::QueryRequest* request, ::LogResults* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniSplunk::Service::SearchKeyword(::grpc::ServerContext* context, const ::QueryRequest* request, ::LogResults* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniSplunk::Service::CountKeyword(::grpc::ServerContext* context, const ::QueryRequest* request, ::LogCount* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


